# -*- coding: utf-8 -*-
"""Demand Forecasting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oFM30COph44AJ1rVJKDG5xTxNKuVJyWw
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from xgboost import XGBRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error , mean_squared_error , r2_score

"""## Load Data"""

df = pd.read_csv('/content/trips_hourly_analytical.csv' , parse_dates=['hour_ts'])

"""## Check for Missing Values"""

df.isna().sum()

"""## Handle Missing 'event_name' Values"""

df['event_name'] = df['event_name'].fillna("None")

"""## Sort Data and Display Head"""

df = df.sort_values(['zone_name' , 'hour_ts']).reset_index(drop=True)

df.head()

"""## Visualization"""

# Demand by hour of day
hourly = df.groupby('hour_ts')['demand'].mean()
hourly = df.groupby(df['hour_ts'].dt.hour)['demand'].mean()

plt.figure(figsize=(8, 5))
sns.lineplot(x=hourly.index, y=hourly.values, marker='o')
plt.title("Average Demand by Hour of Day")
plt.xlabel("Hour")
plt.ylabel("Average Trips")
plt.xticks(range(0,24,2))
plt.tight_layout()
plt.show()

# Demand by zone

zone_demand = df.groupby('zone_name')['demand'].mean().sort_values(ascending=False)

plt.figure(figsize=(8, 5))
sns.barplot(x=zone_demand.values, y=zone_demand.index, color="#DD8452")
plt.title("Average Demand by Zone")
plt.xlabel("Average Trips per Hour")
plt.ylabel("Zone")
for i, v in enumerate(zone_demand.values):
    plt.text(v + 0.1, i, f"{v:.1f}", va='center')
plt.tight_layout()
plt.show()

# Demand by day of week

day_demand = df.groupby('day_name')['demand'].mean()
order = ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday']
day_demand = day_demand.reindex(order)

plt.figure(figsize=(8, 5))
sns.barplot(x=day_demand.index, y=day_demand.values, color="#4C72B0")
plt.title("Average Demand by Day of Week")
plt.xlabel("Day")
plt.ylabel("Average Trips")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""## Analyze Demand during Ramadan vs. Normal Days"""

ramadan = df[df['is_ramadan'] == 1].groupby(df['hour_ts'].dt.hour)['demand'].mean()
normal = df[df['is_ramadan'] == 0].groupby(df['hour_ts'].dt.hour)['demand'].mean()

plt.figure(figsize=(8, 5))
plt.plot(normal.index, normal.values, marker='o', label='Normal Days')
plt.plot(ramadan.index, ramadan.values, marker='o', label='Ramadan')
plt.title("Demand by Hour : Ramadan vs Normal Days")
plt.xlabel("Hour")
plt.ylabel("Average Trips")
plt.xticks(range(0,24,2))
plt.legend()
plt.tight_layout()
plt.show()

"""## Feature Engineering: Create New Binary Features"""

df['city_side'] = df['city_side'].replace({'Rusafa': 0, 'Karkh': 1})
df['is_rainy'] = (df['rain_mm'] > 0).replace({False: 0, True: 1})
df['is_hot'] = (df['temp_c'] >= 40).replace({False: 0, True: 1})

df['is_special_day'] = (df['event_name'] != "None").replace({False : 0 , True : 1})

"""## Map Day Names to Numerical Representation"""

day_mapping = {'Sunday' : 1 , 'Monday' : 2 , 'Tuesday' : 3 , 'Wednesday' : 4 , 'Thursday' : 5 , 'Friday' : 6 , 'Saturday' : 7}
df['day_name'] = df['day_name'].map(day_mapping)

"""## Extract Hour and Month from Timestamp"""

df['hour'] = df['hour_ts'].dt.hour
df['month'] = df['hour_ts'].dt.month
df[['hour_ts' , 'hour' , 'month' , 'day_name' , 'city_side' , 'is_rainy' , 'is_special_day']].head(5)

"""## One-Hot Encode"""

ohe = OneHotEncoder(handle_unknown='ignore' , sparse_output= False).set_output(transform='pandas')

ohe_tf = ohe.fit_transform(df[['zone_name']])

ohe = OneHotEncoder(handle_unknown='ignore' , sparse_output= False).set_output(transform='pandas')

ohe_tf2 = ohe.fit_transform(df[['zone_type']])

ohe_tf.head()
ohe_tf2.head()

"""## Concatenate One-Hot Encoded Features and Drop Original Columns"""

df = pd.concat([df , ohe_tf , ohe_tf2 ] , axis=1).drop(['zone_type' , 'zone_type'] , axis=1)

"""## Display DataFrame Head After Concatenation"""

df.head()

"""## Display DataFrame Information"""

df.info()

"""## Convert Selected Columns to Integer Type"""

df['city_side'] = df['city_side'].astype(int)
df['is_rainy'] = df['is_rainy'].astype(int)
df['is_rainy'] = df['is_rainy'].astype(int)
df['is_weekend_iraq'] = df['is_weekend_iraq'].astype(int)
df['is_ramadan'] = df['is_ramadan'].astype(int)
df['is_eid'] = df['is_eid'].astype(int)
df['is_public_holiday'] = df['is_public_holiday'].astype(int)
df['is_religious_event'] = df['is_religious_event'].astype(int)
df['is_university_break'] = df['is_university_break'].astype(int)
df['zone_name_Al-Adhamiyah'] = df['zone_name_Al-Adhamiyah'].astype(int)
df['zone_name_Al-Maghreb'] = df['zone_name_Al-Maghreb'].astype(int)
df['zone_name_Al-Mansour'] = df['zone_name_Al-Mansour'].astype(int)
df['zone_name_Al-Yarmouk'] = df['zone_name_Al-Yarmouk'].astype(int)
df['zone_name_Jadriyah'] = df['zone_name_Jadriyah'].astype(int)
df['zone_name_Jamila'] = df['zone_name_Jamila'].astype(int)
df['zone_name_Karada'] = df['zone_name_Karada'].astype(int)
df['zone_name_Zayouna'] = df['zone_name_Zayouna'].astype(int)
df["zone_type_commercial\r"] = df["zone_type_commercial\r"].astype(int)
df["zone_type_market\r"] = df["zone_type_market\r"].astype(int)
df["zone_type_residential\r"] = df["zone_type_residential\r"].astype(int)
df["zone_type_university\r"] = df["zone_type_university\r"].astype(int)

"""## Feature Engineering: Create Lag and Rolling Mean Features"""

df['lag_1'] = df.groupby('zone_name')['demand'].shift(1)
df['lag_24'] = df.groupby('zone_name')['demand'].shift(24)
df['lag_168'] = df.groupby('zone_name')['demand'].shift(168)
df['lag_336'] = df.groupby('zone_name')['demand'].shift(336)

df['roll_mean_24'] = df.groupby('zone_name')['demand'].transform(lambda x: x.shift(1).rolling(24).mean())
df['roll_mean_168'] = df.groupby('zone_name')['demand'].transform(lambda x: x.shift(1).rolling(168).mean())

df[['hour_ts' , 'zone_name' , 'demand' , 'lag_1' , 'lag_24' , 'lag_168']].head(5)

"""## Drop Rows with NaN Values from Lag Features"""

df = df.dropna(subset=['lag_1' , 'lag_24' , 'lag_168' , 'lag_336']).reset_index(drop=True)

"""## Define Features (X) and Target (y)"""

X = df.drop(['hour_ts' , 'zone_name' , 'demand' , 'event_name' , 'total_requests' , 'no_driver_found' , 'cancelled'] , axis=1)
y = df['demand']

X.shape , y.shape

"""## Split Data into Training and Testing Sets and Scale Features"""

split_date = '2026-02-18'

X_train = X[df['hour_ts'] < split_date]
X_test = X[df['hour_ts'] >= split_date]

y_train = y[df['hour_ts'] < split_date]
y_test = y[df['hour_ts'] >= split_date]

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Train:" , X_train.shape , " Test:" , X_test.shape)

"""## Evaluate Baseline Model Performance"""

baseline_pred = X_test['lag_168']

print('baseline performence:')
print('---------------------')
print('MAE:',mean_absolute_error(y_test ,baseline_pred))
print('RMS:',np.sqrt(mean_squared_error(y_test ,baseline_pred)))
print('R2:',r2_score(y_test ,baseline_pred))

"""## Train and Evaluate XGBoost Model"""

xgb_model = XGBRegressor(random_state=42, n_estimators=500, learning_rate=0.05, max_depth=6)
xgb_model.fit(X_train, y_train)

xgb_pred = xgb_model.predict(X_test)
xgb_pred = np.clip(xgb_pred, 0, None)

print("XGBoost Model Performance:")
print('---------------------')
print("MAE:", mean_absolute_error(y_test, xgb_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, xgb_pred)))
print("R2:", r2_score(y_test, xgb_pred))

"""## Visualize Actual vs. Predicted Demand for Karada Zone"""

# Actual vs Predicted for Karada , first 2 weeks of the test period

results = X_test.copy()
results['hour_ts'] = df['hour_ts'][X_test.index]
results['zone_name'] = df['zone_name'][X_test.index]
results['actual'] = y_test
results['predicted'] = xgb_pred

karada = results[results['zone_name'] == 'Karada'].sort_values('hour_ts').head(24*14)

plt.figure(figsize=(14, 5))
plt.plot(karada['hour_ts'], karada['actual'], label='Actual')
plt.plot(karada['hour_ts'], karada['predicted'], label='Predicted')
plt.title("Karada : Actual vs Predicted Demand")
plt.xlabel("Date")
plt.ylabel("Trips per Hour")
plt.legend()
plt.tight_layout()
plt.show()

"""## Compare Model Performance (XGBoost vs. Baseline)"""

model_comparison = pd.DataFrame({
    'Model': [
        'XGBoost' ,'Baseline (last week)'],

    'MAE': [
        mean_absolute_error(y_test, xgb_pred),
        mean_absolute_error(y_test, baseline_pred)


    ],
    'RMSE': [
        np.sqrt(mean_squared_error(y_test, xgb_pred)),
        np.sqrt(mean_squared_error(y_test, baseline_pred))


    ],
    'R2': [
        r2_score(y_test, xgb_pred),
        r2_score(y_test, baseline_pred)
    ]
})

model_comparison

"""## Calculate Mean Absolute Percentage Error (MAPE)"""

mask = y_test >= 1

mape_baseline = np.mean(np.abs((y_test[mask] - baseline_pred[mask]) / y_test[mask])) * 100
mape_xgb = np.mean(np.abs((y_test[mask] - xgb_pred[mask]) / y_test[mask])) * 100

print("MAPE Baseline:", round(mape_baseline, 2), "%")
print("MAPE XGBoost:", round(mape_xgb, 2), "%")

"""## Analyze Model Bias"""

# checking if the model is biased

bias = (xgb_pred - y_test).mean()
print("Average error (bias):", round(bias, 3))

print("Average demand in the train period:", round(y_train.mean(), 2))
print("Average demand in the test period :", round(y_test.mean(), 2))

"""## Visualize Feature Importances"""

# Feature Importances

importances = xgb_model.feature_importances_
feature_names = X.columns

feat_imp = pd.DataFrame({
    'Feature': feature_names,
    'Importance': importances
}).sort_values('Importance', ascending=False)

top15 = feat_imp.head(15)

plt.figure(figsize=(8, 6))
plt.barh(top15['Feature'], top15['Importance'], color="#4C72B0")
plt.gca().invert_yaxis()
plt.xlabel('Importance')
plt.title('Top 15 Features - XGBoost')
plt.tight_layout()
plt.show()

"""## Analyze Errors on Normal vs. Special Days and by Zone"""

# how big is the error on normal days vs special days

results['error'] = results['predicted'] - results['actual']
results['abs_error'] = results['error'].abs()

results['is_ramadan'] = df['is_ramadan'][X_test.index]

print("MAE on normal days :", results[results['is_ramadan'] == 0]['abs_error'].mean())
print("MAE on Ramadan days:", results[results['is_ramadan'] == 1]['abs_error'].mean())

# error by zone

zone_error = results.groupby('zone_name').agg(
    avg_demand = ('actual' , 'mean'),
    MAE = ('abs_error' , 'mean')
).sort_values('MAE', ascending=False)

zone_error

"""## Export Predictions for Power BI"""

# saving the predictions so Power BI can read them

export = pd.DataFrame({
    'hour_ts': df['hour_ts'][X_test.index],
    'zone_name': df['zone_name'][X_test.index],
    'latitude': df['latitude'][X_test.index],
    'longitude': df['longitude'][X_test.index],
    'hour': df['hour'][X_test.index],
    'day_name': df['day_name'][X_test.index],
    'actual_demand': y_test,
    'predicted_demand': np.round(xgb_pred, 2),
    'is_ramadan': df['is_ramadan'][X_test.index],
    'is_weekend_iraq': df['is_weekend_iraq'][X_test.index],
    'total_requests': df['total_requests'][X_test.index],
    'no_driver_found': df['no_driver_found'][X_test.index],
    'cancelled': df['cancelled'][X_test.index]
})

export['error'] = (export['predicted_demand'] - export['actual_demand']).round(2)
export['abs_error'] = export['error'].abs()

export.to_csv('predictions_for_powerbi.csv' , index=False)

print(export.shape)
export.head(5)